c_stdlib_version:          # [osx]
  - '11.0'                 # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - '11.0'                 # [osx]

c_stdlib_version:          # [linux]
  - 2.17                   # [linux]

build_variant:
  - "qt5"
  - "qt6"
