{% set name = "quazip" %}
{% set version = "1.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stachenov/quazip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 79633fd3a18e2d11a7d5c40c4c79c1786ba0c74b59ad752e8429746fe1781dd6

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('quazip', max_pin='x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - qt-main
    - zlib
  run:
    - qt-main
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libquazip1-qt5.so  # [linux]

about:
  home: https://stachenov.github.io/quazip/
  license: GPL-2.0-only
  license_family: GPL2
  license_file: COPYING
  summary: Qt/C++ wrapper over minizip

extra:
  recipe-maintainers:
    - izahn
