{% set name = "quazip" %}
{% set version = "1.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stachenov/quazip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 61c73926d4e98bf4c38becc15ba10437ab2af9e746a3982b86f7d720bd5823b4

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('quazip', max_pin='x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - qt6-main
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libquazip1-qt6.so  # [linux]

about:
  home: https://stachenov.github.io/quazip/
  license: GPL-2.0-only
  license_family: GPL2
  license_file: COPYING
  summary: Qt/C++ wrapper over minizip

extra:
  recipe-maintainers:
    - izahn
    - effigies
