{% set name = "quazip" %}
{% set version = "1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stachenov/quazip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c1239559cd6860cab80a0fd81f4204e606f9324f702dab6166b0960676ee1754

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('quazip', max_pin='x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - qt
    - zlib
  run:
    - qt
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libquazip1-qt5.so  # [linux]

about:
  home: https://stachenov.github.io/quazip/
  license: GPL-2.0-only
  license_family: GPL2
  license_file: COPYING
  summary: Qt/C++ wrapper over minizip

extra:
  recipe-maintainers:
    - izahn
